#ifndef _CTAPHID_H_
#define _CTAPHID_H_

// CTAPHID Capabilities
#define CTAPHID_CAPABILITY_WINK 0x1
#define CTAPHID_CAPABILITY_CBOR 0x4
#define CTAPHID_CAPABILITY_NMSG 0x8

// CTAPHID Protocol Version (CTAP2)
#define CTAPHID_PROTOCOL_VERSION 2

// CTAPHID Commands
#define CTAPHID_PING 0x1
#define CTAPHID_INIT 0x6
#define CTAPHID_WINK 0x8
#define CTAPHID_ERROR 0x3f

// CTAPHID Errors
#define CTAPHID_ERR_INVALID_CMD 0x01
#define CTAPHID_ERR_INVALID_PAR 0x02
#define CTAPHID_ERR_INVALID_LEN 0x03
#define CTAPHID_ERR_INVALID_SEQ 0x04
#define CTAPHID_ERR_MSG_TIMEOUT 0x05
#define CTAPHID_ERR_CHANNEL_BUSY 0x06
#define CTAPHID_ERR_LOCK_REQUIRED 0x0A
#define CTAPHID_ERR_INVALID_CHANNEL 0x0B
#define CTAPHID_ERR_OTHER 0x7F

#endif